// Generated by https://quicktype.io

export interface IUsersResponse {
  users: User[];
}

export interface IUserResponse {
  users: User;
}

export interface User {
  _id: string | undefined;
  name: string;
  age: number;
  email: string;
}
